on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: thomasnordquist/mqtt-explorer-ui-tests:latest
  test:
    runs-on: ubuntu-latest
    container:
      image: thomasnordquist/mqtt-explorer-ui-tests:latest
      volumes:
        - ./:/app
    steps:
      - name: Install Packages
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Install Packages
        run: yarn ui-test
